/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ChocoBun (https://sketchfab.com/ChocoBun)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/neon-choco-plush-a0a1b8a914f54f73ba5d2b9f25d592c2
title: "Neon" Choco Plush
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/mod.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.8}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material}
        />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Solid} />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Solid.001"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["model.001"]}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["model.002"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["model.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mod.gltf");
