/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jil Shah (https://sketchfab.com/jil31)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dragon-glass-fe00cb0ecaca4e4595874b70de7e116b
title: Dragon Glass
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/mod1.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} scale={0.15}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0, 0, 0.53]}
          rotation={[-Math.PI / 2, 1, 5]}
        >
          <group name="24e86ff21e6040788ab27f301f1f4180abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group
                  name="Object_40"
                  position={[0, 5.38, -4.23]}
                  rotation={[2.9, -0.19, -0.24]}
                  scale={0.11}
                >
                  <group name="TimeframeMainGroup">
                    <group name="Object_42">
                      <mesh
                        name="polySurface5_000Shape_22_0"
                        geometry={nodes.polySurface5_000Shape_22_0.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_44" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_1"
                        geometry={nodes.polySurface5_000Shape_22_1.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_46" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_2"
                        geometry={nodes.polySurface5_000Shape_22_2.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_48" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_3"
                        geometry={nodes.polySurface5_000Shape_22_3.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_50" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_4"
                        geometry={nodes.polySurface5_000Shape_22_4.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_52" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_5"
                        geometry={nodes.polySurface5_000Shape_22_5.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_54" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_6"
                        geometry={nodes.polySurface5_000Shape_22_6.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_56" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_7"
                        geometry={nodes.polySurface5_000Shape_22_7.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_58" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_8"
                        geometry={nodes.polySurface5_000Shape_22_8.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_60" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_9"
                        geometry={nodes.polySurface5_000Shape_22_9.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_62" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_10"
                        geometry={nodes.polySurface5_000Shape_22_10.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_64" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_11"
                        geometry={nodes.polySurface5_000Shape_22_11.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_66" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_12"
                        geometry={nodes.polySurface5_000Shape_22_12.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_68" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_13"
                        geometry={nodes.polySurface5_000Shape_22_13.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_70" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_14"
                        geometry={nodes.polySurface5_000Shape_22_14.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_72" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_15"
                        geometry={nodes.polySurface5_000Shape_22_15.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_74" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_16"
                        geometry={nodes.polySurface5_000Shape_22_16.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_76" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_17"
                        geometry={nodes.polySurface5_000Shape_22_17.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_78" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_18"
                        geometry={nodes.polySurface5_000Shape_22_18.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_80" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_19"
                        geometry={nodes.polySurface5_000Shape_22_19.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_82" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_20"
                        geometry={nodes.polySurface5_000Shape_22_20.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_84" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_21"
                        geometry={nodes.polySurface5_000Shape_22_21.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_86" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_22"
                        geometry={nodes.polySurface5_000Shape_22_22.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_88" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_23"
                        geometry={nodes.polySurface5_000Shape_22_23.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_90" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_24"
                        geometry={nodes.polySurface5_000Shape_22_24.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_92" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_25"
                        geometry={nodes.polySurface5_000Shape_22_25.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_94" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_26"
                        geometry={nodes.polySurface5_000Shape_22_26.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_96" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_27"
                        geometry={nodes.polySurface5_000Shape_22_27.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_98" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_28"
                        geometry={nodes.polySurface5_000Shape_22_28.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_100" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_29"
                        geometry={nodes.polySurface5_000Shape_22_29.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_102" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_30"
                        geometry={nodes.polySurface5_000Shape_22_30.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_104" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_31"
                        geometry={nodes.polySurface5_000Shape_22_31.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_106" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_32"
                        geometry={nodes.polySurface5_000Shape_22_32.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_108" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_33"
                        geometry={nodes.polySurface5_000Shape_22_33.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_110" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_34"
                        geometry={nodes.polySurface5_000Shape_22_34.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_112" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_35"
                        geometry={nodes.polySurface5_000Shape_22_35.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_114" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_36"
                        geometry={nodes.polySurface5_000Shape_22_36.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_116" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_37"
                        geometry={nodes.polySurface5_000Shape_22_37.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_118" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_38"
                        geometry={nodes.polySurface5_000Shape_22_38.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                    <group name="Object_120" scale={0}>
                      <mesh
                        name="polySurface5_000Shape_22_39"
                        geometry={nodes.polySurface5_000Shape_22_39.geometry}
                        material={materials.polySurface5_000Shape}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Object_122"
                  position={[0, 5.38, -4.23]}
                  rotation={[2.9, -0.19, -0.24]}
                  scale={0.11}
                >
                  <group name="MorphMainGroup">
                    <mesh
                      name="polySurface5_001Shape"
                      geometry={nodes.polySurface5_001Shape.geometry}
                      material={materials.polySurface5_001Shape}
                      morphTargetDictionary={
                        nodes.polySurface5_001Shape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.polySurface5_001Shape.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_4" rotation={[0, 0, Math.PI]}>
                  <group name="TimeframeMainGroup_1">
                    <group name="Object_6">
                      <mesh
                        name="Plane_006Shape_2_0"
                        geometry={nodes.Plane_006Shape_2_0.geometry}
                        material={materials.Plane_006Shape}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_8" position={[0, 0.05, 0]}>
                  <group name="TimeframeMainGroup_2">
                    <group name="Object_10">
                      <mesh
                        name="PlaneShape_4_0"
                        geometry={nodes.PlaneShape_4_0.geometry}
                        material={materials.PlaneShape}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Object_12"
                  position={[0, -0.05, 0]}
                  rotation={[0, 0, Math.PI]}
                >
                  <group name="TimeframeMainGroup_3">
                    <group name="Object_14">
                      <mesh
                        name="Plane_001Shape_6_0"
                        geometry={nodes.Plane_001Shape_6_0.geometry}
                        material={materials.Plane_001Shape}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_16" position={[0.27, 6.54, 2.01]}>
                  <group name="TimeframeMainGroup_4">
                    <group name="Object_18">
                      <mesh
                        name="IcosphereShape_8_0"
                        geometry={nodes.IcosphereShape_8_0.geometry}
                        material={materials.IcosphereShape}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_20" position={[0.27, 6.54, 2.01]}>
                  <group name="TimeframeMainGroup_5">
                    <group name="Object_22">
                      <mesh
                        name="Icosphere_002Shape_10_0"
                        geometry={nodes.Icosphere_002Shape_10_0.geometry}
                        material={materials.Icosphere_002Shape}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_24" position={[0.47, -3.94, -3.42]}>
                  <group name="TimeframeMainGroup_6">
                    <group name="Object_26">
                      <mesh
                        name="Icosphere_003Shape_12_0"
                        geometry={nodes.Icosphere_003Shape_12_0.geometry}
                        material={materials.Icosphere_003Shape}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Object_28"
                  rotation={[-Math.PI, 0, 0]}
                  scale={0.69}
                >
                  <group name="TimeframeMainGroup_7">
                    <group name="Object_30">
                      <mesh
                        name="Plane_002Shape_14_0"
                        geometry={nodes.Plane_002Shape_14_0.geometry}
                        material={materials.Plane_002Shape}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_32" rotation={[0, 0, Math.PI]}>
                  <group name="TimeframeMainGroup_8">
                    <group name="Object_34">
                      <mesh
                        name="Plane_003Shape_16_0"
                        geometry={nodes.Plane_003Shape_16_0.geometry}
                        material={materials.Plane_003Shape}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_36" rotation={[0, 0, Math.PI]}>
                  <group name="TimeframeMainGroup_9">
                    <group name="Object_38">
                      <mesh
                        name="Plane_004Shape_20_0"
                        geometry={nodes.Plane_004Shape_20_0.geometry}
                        material={materials.Plane_004Shape}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mod1.gltf");
