/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: QumoDone (https://sketchfab.com/QumoDone)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-mushrooms-9d22e02ce2a548959b1c4c4c1d546842
title: Stylized mushrooms
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/mod2.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 3, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.008}>
          <mesh
            geometry={nodes.Circle_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Circle001_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Plane_ground_0.geometry}
            material={materials.ground}
          />
          <mesh
            geometry={nodes.Circle002_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Circle005_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere004_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Plane001_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Plane002_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Circle006_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Circle004_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Cube_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Cube001_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere006_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere007_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere008_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere009_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere010_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere001_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere002_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere003_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere005_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere011_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Icosphere012_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Plane003_mushroms_0.geometry}
            material={materials.mushroms}
          />
          <mesh
            geometry={nodes.Plane004_ground_0.geometry}
            material={materials.ground}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mod2.gltf");
